### ISSUE TITLE
Creating a new project doesn't install dependancies correctly

### ISSUE THREAD

**Issue by AnthonyPorthouse** [laravel/lumen-installer#1]
After creating a new project I had to delete the vendor folder and then re-run `composer install` to be able to run `phpunit` as permissions are incorrect. After correcting permissions I receieve the following error: 

```
You need to set up the project dependencies using the following commands:
wget http://getcomposer.org/composer.phar
php composer.phar install
```

The full list of commands issued was as follows:
![](http://i.imgur.com/k2aFNYv.png)

**Comment by tomcastleman** [comment]
This is actually due to symlinks not being correctly setup by the laravel/lumen-installer (and the laravel/installer upon which it is based). A detailed description and a workaround fix for this problem can be found on this thread:

https://laracasts.com/discuss/channels/general-discussion/phpunit-woes

A fix was proposed by @jildertmiedema for the laravel/installer here:

https://github.com/laravel/installer/pull/26

But I'm not sure whether this PR has fixed the problem as this commit hasn't yet been made available in a release (1.2.0 is the current release).
